In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[3.0009e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4309, 0.1517, 0.5958],
        [0.0114, 0.9322, 0.2937],
        [0.9241, 0.6324, 0.8350],
        [0.2868, 0.3728, 0.4542],
        [0.5558, 0.6680, 0.7339]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1057,  1.8785, -0.9271],
        [-0.1698, -0.2046,  0.2087],
        [-1.1750, -0.2660,  0.4914],
        [-1.6466, -1.3790, -0.2157],
        [-0.8281, -0.3960,  0.2232]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
print(x.shape)

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1851,  2.1805, -0.4884],
        [ 0.4727,  0.2068,  1.0895],
        [-0.2495, -0.2443,  1.4066],
        [-1.4868, -1.0728,  0.7515],
        [-0.5231,  0.3304,  1.1768]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))

tensor([[-0.1851,  2.1805, -0.4884],
        [ 0.4727,  0.2068,  1.0895],
        [-0.2495, -0.2443,  1.4066],
        [-1.4868, -1.0728,  0.7515],
        [-0.5231,  0.3304,  1.1768]])


Addition: providing an output tensor as argument



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1851,  2.1805, -0.4884],
        [ 0.4727,  0.2068,  1.0895],
        [-0.2495, -0.2443,  1.4066],
        [-1.4868, -1.0728,  0.7515],
        [-0.5231,  0.3304,  1.1768]])


Addition: in-place



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.1851,  2.1805, -0.4884],
        [ 0.4727,  0.2068,  1.0895],
        [-0.2495, -0.2443,  1.4066],
        [-1.4868, -1.0728,  0.7515],
        [-0.5231,  0.3304,  1.1768]])


In [19]:
x

tensor([[-1.1057,  1.8785, -0.9271],
        [-0.1698, -0.2046,  0.2087],
        [-1.1750, -0.2660,  0.4914],
        [-1.6466, -1.3790, -0.2157],
        [-0.8281, -0.3960,  0.2232]])

In [52]:
x[:2 , :3]

tensor([[-1.1057,  1.8785, -0.9271],
        [-0.1698, -0.2046,  0.2087]])

<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [53]:
print(x[:, 1])

tensor([ 1.8785, -0.2046, -0.2660, -1.3790, -0.3960])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [55]:
x = torch.randn(4, 4)
x

tensor([[-0.4597, -0.0892, -0.5660,  0.2494],
        [ 0.6062, -0.5172,  0.2535,  1.5300],
        [-0.1195, -0.9945,  2.0111,  1.5523],
        [ 0.1977,  0.4999,  0.6410,  0.1596]])

In [64]:
y = x.view(8,2)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([8, 2]) torch.Size([2, 8])


In [65]:
y

tensor([[-0.4597, -0.0892],
        [-0.5660,  0.2494],
        [ 0.6062, -0.5172],
        [ 0.2535,  1.5300],
        [-0.1195, -0.9945],
        [ 2.0111,  1.5523],
        [ 0.1977,  0.4999],
        [ 0.6410,  0.1596]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [4]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5270])
-0.5269631743431091


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [12]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [13]:
a.add(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!